SCREEN_WIDTH = 1400
SCREEN_HEIGHT = 1000

BULLET_RADIUS = 30
BULLET_SPEED = 10
BULLET_LIFE = 60

SHIP_TURN_AMOUNT = 3
SHIP_THRUST_AMOUNT = 0.05
SPEED = 0
SHIP_RADIUS = 30

INITIAL_ROCK_COUNT = 5

BIG_ROCK_SPIN = 1
BIG_ROCK_SPEED = 1.5
BIG_ROCK_RADIUS = 15

MEDIUM_ROCK_SPIN = -2
MEDIUM_ROCK_RADIUS = 5

SMALL_ROCK_SPIN = 5
SMALL_ROCK_RADIUS = 2

MUSIC_VOLUME = 2.0

PATH = r'F:\Folders\CS210\Asteroids improved\game\assets\textures'
PATH2 = r'F:\Folders\CS210\Asteroids improved\game\assets\sounds'